casavo/charts

- charts/fe-nextjs/Chart.yaml
- charts/fe-nextjs/templates/_helpers.tpl
- charts/fe-static/Chart.yaml
- charts/fe-static/templates/_helpers.tpl
> chore: use image.tag for appVersion in fe charts

- charts/fe-nextjs/Chart.yaml
- charts/fe-nextjs/templates/deployment.yaml
- charts/fe-nextjs/templates/service.yaml
- charts/fe-nextjs/values.yaml
- charts/fe-static/Chart.yaml
- charts/fe-static/templates/deployment.yaml
- charts/fe-static/templates/service.yaml
- charts/fe-static/values.yaml
> feat: allow to customise container port in FE charts

- charts/be-multisvc/Chart.yaml
- charts/be-multisvc/templates/_helpers.tpl
- charts/be-multisvc/templates/config.yaml
- charts/be-multisvc/templates/cronjob.yaml
- charts/be-multisvc/templates/deployment.yaml
- charts/be-multisvc/templates/hooks/job.yaml
- charts/be-multisvc/templates/hpa.yaml
- charts/be-multisvc/templates/ingress.yaml
- charts/be-multisvc/templates/pdb.yaml
- charts/be-multisvc/templates/podmonitor.yaml
- charts/be-multisvc/templates/prometheus-rule.yaml
- charts/be-multisvc/templates/service.yaml
- charts/be-multisvc/templates/servicemonitor.yaml
- charts/be-multisvc/templates/worker.yaml
- charts/be-multisvc/values.yaml
- charts/be-web/Chart.yaml
- charts/be-web/templates/cronjob.yaml
- charts/be-web/templates/deployment.yaml
- charts/be-web/templates/hooks/job.yaml
- charts/be-web/templates/worker.yaml
> feat: add `be-multisvc` chart (#5)

- charts/be-multisvc/Chart.yaml
- charts/be-multisvc/templates/cronjob.yaml
- charts/be-multisvc/templates/hooks/job.yaml
- charts/be-multisvc/templates/worker.yaml
- charts/be-multisvc/values.yaml
- charts/be-web/Chart.yaml
- charts/be-web/templates/cronjob.yaml
- charts/be-web/templates/hooks/job.yaml
- charts/be-web/templates/worker.yaml
- charts/be-web/values.yaml
> feat: align env customisation in `be` charts

- charts/be-multisvc/Chart.yaml
- charts/be-multisvc/templates/ingress.yaml
> chore: fix ingress template in `be-multisvc` chart

- charts/be-multisvc/Chart.yaml
- charts/be-multisvc/templates/_helpers.tpl
- charts/be-multisvc/templates/cronjob.yaml
- charts/be-multisvc/templates/deployment.yaml
- charts/be-multisvc/templates/hooks/job.yaml
- charts/be-multisvc/templates/service.yaml
- charts/be-multisvc/templates/worker.yaml
- charts/be-web/Chart.yaml
- charts/be-web/templates/_helpers.tpl
- charts/be-web/templates/cronjob.yaml
- charts/be-web/templates/deployment.yaml
- charts/be-web/templates/hooks/job.yaml
- charts/be-web/templates/worker.yaml
- charts/fe-nextjs/Chart.yaml
- charts/fe-nextjs/templates/_helpers.tpl
- charts/fe-nextjs/templates/deployment.yaml
- charts/fe-static/Chart.yaml
- charts/fe-static/templates/_helpers.tpl
- charts/fe-static/templates/deployment.yaml
> chore: use `Release.Name` in place of `Chart.name` for labels

- charts/be-multisvc/Chart.yaml
- charts/be-web/Chart.yaml
- charts/be-web/values.yaml
- charts/fe-nextjs/Chart.yaml
- charts/fe-nextjs/values.yaml
- charts/fe-static/Chart.yaml
- charts/fe-static/values.yaml
> fix: `VolumeMounts` typo

- charts/be-multisvc/Chart.yaml
- charts/be-multisvc/templates/cronjob.yaml
- charts/be-multisvc/templates/hooks/job.yaml
- charts/be-multisvc/templates/worker.yaml
- charts/be-web/Chart.yaml
- charts/be-web/templates/cronjob.yaml
- charts/be-web/templates/hooks/job.yaml
- charts/be-web/templates/worker.yaml
> chore: use root image info in components defaults

- charts/be-multisvc/Chart.yaml
- charts/be-multisvc/templates/hooks/job.yaml
- charts/be-web/Chart.yaml
- charts/be-web/templates/hooks/job.yaml
> chore: remove confimap ref from hooks

- charts/be-multisvc/Chart.yaml
- charts/be-multisvc/templates/deployment.yaml
- charts/be-multisvc/templates/service.yaml
- charts/be-web/Chart.yaml
- charts/be-web/templates/deployment.yaml
- charts/be-web/templates/service.yaml
> feat: add support for multiple ports services in be charts

- charts/fe-nextjs/Chart.yaml
- charts/fe-nextjs/templates/deployment.yaml
> fix: `fe-nextjs` probes

- charts/be-multisvc/Chart.yaml
- charts/be-multisvc/templates/config.yaml
- charts/be-multisvc/templates/deployment.yaml
- charts/be-multisvc/values.yaml
- charts/be-web/Chart.yaml
- charts/be-web/templates/config.yaml
- charts/be-web/templates/deployment.yaml
- charts/be-web/values.yaml
> feat: add `configVolume` to be charts

- charts/be-multisvc/Chart.yaml
- charts/be-multisvc/templates/deployment.yaml
- charts/be-multisvc/templates/podmonitor.yaml
- charts/be-multisvc/values.yaml
- charts/be-web/Chart.yaml
- charts/be-web/templates/deployment.yaml
- charts/be-web/templates/podmonitor.yaml
- charts/be-web/values.yaml
> feat: add support for sidecar containers in `be` charts

- charts/be-multisvc/Chart.yaml
- charts/be-multisvc/templates/podmonitor.yaml
- charts/be-web/Chart.yaml
- charts/be-web/templates/deployment.yaml
- charts/be-web/templates/podmonitor.yaml
> fix: podMonitor ports references

- charts/be-web/Chart.yaml
- charts/be-web/templates/cronjob.yaml
- charts/be-web/templates/service.yaml
- fix(be-web): cronjob schedule quote
- fix(be-web): access global scope from loop
- chore(be-web): version 0.8.3
> be web fixes

- charts/be-multisvc/Chart.yaml
- charts/be-multisvc/templates/cronjob.yaml
- charts/be-multisvc/templates/worker.yaml
> chore: fix `be-multisvc` defaults

- charts/be-multisvc/Chart.yaml
- charts/be-multisvc/templates/cronjob.yaml
- charts/be-multisvc/templates/deployment.yaml
- charts/be-multisvc/templates/secret.yaml
- charts/be-multisvc/templates/worker.yaml
- charts/be-multisvc/values.yaml
- charts/be-web/Chart.yaml
- charts/be-web/templates/cronjob.yaml
- charts/be-web/templates/deployment.yaml
- charts/be-web/templates/secret.yaml
- charts/be-web/templates/worker.yaml
- charts/be-web/values.yaml
> feat: add secrets management in be charts

- charts/be-multisvc/templates/podmonitor.yaml
- charts/be-multisvc/templates/worker.yaml
- charts/be-multisvc/values.yaml
- charts/be-web/templates/podmonitor.yaml
- charts/be-web/templates/worker.yaml
- charts/be-web/values.yaml
> refactor: metrics collection from workers

- charts/be-multisvc/Chart.yaml
- charts/be-multisvc/templates/podmonitor.yaml
- charts/be-multisvc/templates/worker.yaml
- charts/be-multisvc/values.yaml
- charts/be-web/Chart.yaml
- charts/be-web/templates/podmonitor.yaml
- charts/be-web/templates/worker.yaml
- charts/be-web/values.yaml
With this pr we are able to use the worker selector labels whith the podmonitors
> feat(podmonitors): enabled for workers

- charts/fe-nextjs/Chart.yaml
- charts/fe-nextjs/templates/proxy.yaml
> fix: `fe-nextjs` proxy ingress

- charts/be-multisvc/Chart.yaml
- charts/be-multisvc/templates/hooks/config.yaml
- charts/be-multisvc/templates/hooks/job.yaml
- charts/be-multisvc/templates/hooks/secret.yaml
- charts/be-multisvc/templates/podmonitor.yaml
- charts/be-multisvc/values.yaml
- charts/be-web/Chart.yaml
- charts/be-web/templates/hooks/config.yaml
- charts/be-web/templates/hooks/job.yaml
- charts/be-web/templates/hooks/secret.yaml
- charts/be-web/templates/podmonitor.yaml
- charts/be-web/values.yaml
> feat: add hooks configmaps and secrets

- charts/redirects/Chart.yaml
- charts/redirects/templates/_helpers.tpl
- charts/redirects/templates/ingress.yaml
- charts/redirects/values.yaml
> feat: add redirects chart

- charts/redirects/Chart.yaml
- charts/redirects/templates/_helpers.tpl
> fix: redirects chart ingress names

- charts/be-web/Chart.yaml
- charts/be-web/templates/cronjob.yaml
- charts/be-web/templates/deployment.yaml
- charts/be-web/templates/worker.yaml
- charts/be-web/values.yaml
> feat: add serviceAccount to `be-web` chart

- charts/raw/Chart.yaml
- charts/raw/templates/_helpers.tpl
- charts/raw/templates/resources.yaml
- charts/raw/values.yaml
> feat: add raw chart

- charts/be-web/templates/scaledobject.yaml
- charts/be-web/values.yaml
> chore: keda abstraction layer on `be-web` chart
